### ISSUE TITLE
Caddy installation is failing

### ISSUE THREAD

**Issue by oskarbarcz** [damlys/phpdock#11]
Hi damlys, 

I just found out that Caddy installation instructions changed (so as GPG key format in cloudsmith website). 

Here's a little improvement you can consider, it's simply fixing the problem:
https://github.com/damlys/phpdock/pull/10/files

Here's issue on Caddy repo:
https://github.com/caddyserver/dist/issues/83

**Comment by damlys** [comment]
Found the same solution within [Caddy docs](https://caddyserver.com/docs/install#debian-ubuntu-raspbian). Thanks! 🙂
